# 📘 NumPy Masterclass – Part 3
## Linear Algebra, Random Module, File I/O, Performance & Real-World Applications

## 1. Linear Algebra

In [ ]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
A = np.array([[1,2],[3,4]])
# Create a NumPy array from a Python list
B = np.array([[5,6],[7,8]])

print("Dot Product:\n", np.dot(A,B))
print("Matrix Multiplication:\n", A @ B)
# The @ operator is just a shortcut for matrix multiplication.

Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [2]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
A = np.array([[4,7],[2,6]])

print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))
# Transpose array (swap rows and columns)
print("Transpose:\n", A.T)

Determinant: 10.000000000000002
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Transpose:
 [[4 2]
 [7 6]]


In [2]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
A = np.array([[4,2],[1,3]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## 2. Random Module

In [3]:
# Import NumPy with standard alias np
import numpy as np

np.random.seed(42)

# Generate random floats between 0 and 1
print(np.random.rand(3))
# Generate random integers in a range
print(np.random.randint(1,100,5))
print(np.random.choice([10,20,30], size=5))
print(np.random.permutation([1,2,3,4]))

[0.37454012 0.95071431 0.73199394]
[61 21 83 87 75]
[30 10 30 20 10]
[1 3 4 2]


In [ ]:
# Import NumPy with standard alias np
import numpy as np

# Create array with evenly spaced values (start, stop, step)
data=np.arange(10)
np.random.shuffle(data)
print(data)

## 3. Statistical Operations

In [ ]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
arr=np.array([12,18,20,25,30])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std:", np.std(arr))
print("Variance:", np.var(arr))
print("Percentile:", np.percentile(arr,75))

## 4. Correlation

### `np.corrcoef(x, y)`
Returns the **correlation coefficient matrix**, which measures how strongly two arrays are related. A value of `1` means perfect positive correlation, `0` means no correlation, and `-1` means perfect negative correlation.

In [4]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
x=np.array([1,2,3,4,5])
# Create a NumPy array from a Python list
y=np.array([2,4,6,8,10])

print(np.corrcoef(x,y))

[[1. 1.]
 [1. 1.]]


## 5. NumPy File I/O

In [3]:
# Import NumPy with standard alias np
import numpy as np

# Create array with evenly spaced values (start, stop, step)
arr=np.arange(10)

np.save("array.npy",arr)

loaded=np.load("array.npy")

print(loaded)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Import NumPy with standard alias np
import numpy as np

# Create array with evenly spaced values (start, stop, step)
arr=np.arange(12).reshape(3,4)

np.savetxt("matrix.txt",arr,fmt="%d")

loaded=np.loadtxt("matrix.txt")

print(loaded)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


## 6. Structured Arrays

### Structured `dtype`
A structured `dtype` lets each row contain **multiple fields with different data types**, similar to a table or database record. Here, `"name"` is a Unicode string (`U10`) and `"marks"` is a 4-byte integer (`i4`).

In [5]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
students=np.array([
    ("Alice",90),
    ("Bob",82),
    ("Charlie",95)
# Specify data type when creating array
],dtype=[("name","U10"),("marks","i4")])

print(students)
print(students["name"])
print(students["marks"])

[('Alice', 90) ('Bob', 82) ('Charlie', 95)]
['Alice' 'Bob' 'Charlie']
[90 82 95]


## 7. Performance Comparison

In [7]:
# Import NumPy with standard alias np
import numpy as np
import time

python_list=list(range(1_000_000))
# Create array with evenly spaced values (start, stop, step)
numpy_array=np.arange(1_000_000)

start=time.time()
[x*2 for x in python_list]
print("Python:",time.time()-start)

start=time.time()
numpy_array*2
print("NumPy :",time.time()-start)

Python: 0.056971073150634766
NumPy : 0.003991127014160156


## 8. Memory Information

In [8]:
# Import NumPy with standard alias np
import numpy as np

# Create array with evenly spaced values (start, stop, step)
arr=np.arange(100)

# Print memory size of one element (bytes)
print(arr.itemsize)
# Print total memory used by array (bytes)
print(arr.nbytes)
# Print data type of array elements
print(arr.dtype)

8
800
int64


## 9. Real-World Project - Image Matrix

In [9]:
# Import NumPy with standard alias np
import numpy as np

# Generate random integers in a range
image=np.random.randint(0,256,(5,5))

print(image)
# Calculate the mean (average) of array elements
print("Average Brightness:",image.mean())
# Find the maximum value in the array
print("Maximum Pixel:",image.max())

[[139 171 249  81  66]
 [ 88 196   8  85  42]
 [ 54 196 208 140 168]
 [249  48 198 135 199]
 [134 138  95 241  63]]
Average Brightness: 135.64
Maximum Pixel: 249


## 10. Real-World Project - Exam Analytics

In [ ]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
marks=np.array([
    [80,90,70],
    [75,88,92],
    [95,91,89]
])

print("Student Average:",marks.mean(axis=1))
print("Subject Average:",marks.mean(axis=0))
# Find the maximum value in the array
print("Highest:",marks.max())
# Find the minimum value in the array
print("Lowest:",marks.min())

## 11. Best Practices


- Prefer vectorized operations over Python loops.
- Choose appropriate data types to save memory.
- Use broadcasting instead of manual loops.
- Use `np.random.seed()` for reproducible experiments.
- Use `@` for matrix multiplication.


## 12. Common Mistakes


- Confusing `*` with matrix multiplication.
- Forgetting to match array shapes.
- Ignoring broadcasting rules.
- Loading huge files with `loadtxt()` when streaming may be better.


## 13. Practice Exercises


1. Compute matrix inverse.
2. Find eigenvalues of a matrix.
3. Save and reload NumPy arrays.
4. Build a marks analytics system.
5. Generate random datasets.
6. Calculate correlation between two variables.
7. Create a structured employee database.
8. Compare Python list performance with NumPy.


## 14. Interview Questions


1. Why is NumPy fast?
2. Difference between `dot()` and `@`?
3. What are eigenvalues?
4. What is broadcasting?
5. Difference between `.npy` and `.npz`?
6. What is a structured array?
7. Why use `seed()`?
8. Explain vectorization.


# 🎉 NumPy Masterclass Complete

You now understand:

- ndarray fundamentals
- Array creation
- Indexing & slicing
- Reshaping
- Broadcasting
- Vectorization
- Universal functions
- Aggregations
- Boolean masking
- Fancy indexing
- Sorting & searching
- Array manipulation
- Linear algebra
- Random module
- Statistics
- File I/O
- Structured arrays
- Performance optimization
- Real-world applications

You now have a strong NumPy foundation for Pandas, Matplotlib, Scikit-learn, TensorFlow, PyTorch, Data Science, Machine Learning, and AI.
