# 📘 NumPy Masterclass – Part 2
## Vectorization, Indexing, Aggregations & Array Manipulation

## 1. Recap

Part 1 covered array creation, indexing, slicing, reshaping, broadcasting basics, and array attributes.

## 2. Why Vectorization?

In [3]:
# Import NumPy with standard alias np
import numpy as np
import time

# Create array with evenly spaced values (start, stop, step)
numbers = np.arange(1_000_000)

start = time.time()
result = numbers * 2
print("Vectorized Time:", time.time() - start)   

#if same thing would have done by the for loop it would have taken lot much time 
# so directly doing task without for loop is vectorization

Vectorized Time: 0.0019123554229736328


Vectorization performs operations on an entire array without explicit Python loops.

## 3. Universal Functions (ufuncs)

In [4]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.square(arr))
print(np.sin(arr))
print(np.cos(arr))

[1. 2. 3. 4.]
[  1  16  81 256]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


## 4. Aggregation Functions

In [5]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
arr = np.array([10,20,30,40,50])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

150
30.0
30.0
14.142135623730951
200.0
10
50
0
4


### `np.min(arr)`
Returns the **smallest value** in the array.

### `np.max(arr)`
Returns the **largest value** in the array.

### `np.argmin(arr)`
Returns the **index (position)** of the smallest value in the array.

### `np.argmax(arr)`
Returns the **index (position)** of the largest value in the array.

## 5. Understanding the `axis` Parameter

### `axis` in NumPy
- `axis=0` → Perform the operation **column-wise** (down the rows).
- `axis=1` → Perform the operation **row-wise** (across the columns).

In [4]:
# Create a NumPy array from a Python list
matrix = np.array([[1,2,3],
                   [4,5,6]])

print("Sum of all:", matrix.sum())
print("Column sums:", matrix.sum(axis=0))
print("Row sums:", matrix.sum(axis=1))

Sum of all: 21
Column sums: [5 7 9]
Row sums: [ 6 15]


## 6. Boolean Masking

In [5]:
# Create a NumPy array from a Python list
arr = np.array([12,5,30,7,42,18])

mask = arr > 15

print(mask)
# Index array by position (0-based)
print(arr[mask])

[False False  True False  True  True]
[30 42 18]


## 7. Fancy Indexing

In [ ]:
# Create a NumPy array from a Python list
arr = np.array([10,20,30,40,50,60])

# Index array by position (0-based)
print(arr[[0,2,5]])


# Index:  0   1   2   3   4   5
# Value: 10  20  30  40  50  60
#         ↑       ↑           ↑

[10 30 60]


## 8. Sorting & Searching

In [9]:
# Create a NumPy array from a Python list
arr = np.array([40,10,30,20])

print(np.sort(arr))
print(np.argsort(arr))
# Returns the indices that would sort the array.

[10 20 30 40]
[1 3 2 0]


In [ ]:
    # Create a NumPy array from a Python list
    arr = np.array([5,10,15,20])
    # Returns the indices where the condition is True.
    print(np.where(arr > 10))
    # Returns the index where the value should be inserted to keep the array sorted.
    print(np.searchsorted(arr, 18))

(array([2, 3]),)
3


## 9. Array Manipulation

In [6]:
# Create a NumPy array from a Python list
a = np.array([1,2,3])
# Create a NumPy array from a Python list
b = np.array([4,5,6])

print(np.concatenate((a,b)))
print(np.stack((a,b)))
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.arange(12)

print(np.split(arr,3))
print(np.repeat([1,2],3))
# Repeats each element 3 times.
print(np.tile([1,2],4))
# Repeats the entire array 4 times.

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[1 1 1 2 2 2]
[1 2 1 2 1 2 1 2]


## 10. Advanced Broadcasting

In [9]:
# Create a NumPy array from a Python list
matrix = np.array([[1,2,3],
                   [4,5,6]])

# Create a NumPy array from a Python list
vector = np.array([10,20,30])

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


In [10]:
#  1   2   3
#  4   5   6

# +

# 10  20  30
# 10  20  30

# =

# 11 22 33
# 14 25 36

## 11. Useful NumPy Utilities

### `np.unique(arr)`
Returns the **unique values** in the array (duplicates are removed).

### `np.clip(arr, min, max)`
Limits all values to the given range. Values below `min` become `min`, and values above `max` become `max`.

### `np.cumsum(arr)`
Returns the **cumulative (running) sum** of the array.

### `np.cumprod(arr)`
Returns the **cumulative (running) product** of the array.

In [ ]:
# Create a NumPy array from a Python list
arr = np.array([5,2,8,1])
# Returns only the unique values (duplicates removed).

print(np.unique(arr))

# Keeps every value between 2 and 6.
# Values less than 2 become 2.
# Values greater than 6 become 6.

print(np.clip(arr,2,6))

print(np.cumsum(arr))

print(np.cumprod([1,2,3,4]))

[1 2 5 8]
[5 2 6 2]
[ 5  7 15 16]
[ 1  2  6 24]


## 12. Mini Project - Sales Analysis

In [ ]:
# Create a NumPy array from a Python list
sales = np.array([
    [120,150,170],
    [100,130,160],
    [140,180,210]
])

print("Total:", sales.sum())
print("Monthly:", sales.sum(axis=0))
print("Store:", sales.sum(axis=1))
# Calculate the mean (average) of array elements
print("Average:", sales.mean())

## 13. Common Mistakes


- Mixing incompatible shapes.
- Forgetting the `axis` argument.
- Confusing boolean masking with fancy indexing.
- Using Python loops instead of vectorized operations.


## 14. Practice Exercises


1. Find numbers greater than the mean.
2. Sort a matrix row-wise.
3. Compute row and column averages.
4. Stack two matrices vertically.
5. Repeat each element four times.
6. Create a mask for multiples of 5.
7. Find unique values.
8. Compute cumulative sums.


## 15. Interview Questions


1. What is vectorization?
2. What are ufuncs?
3. Explain the `axis` parameter.
4. Difference between boolean masking and fancy indexing?
5. Difference between `concatenate()` and `stack()`?
6. What is broadcasting?


# 🎉 Summary

You learned:
- Vectorization
- Universal Functions
- Aggregations
- Axis
- Boolean Masking
- Fancy Indexing
- Sorting & Searching
- Array Manipulation
- Advanced Broadcasting

➡️ **Next Notebook:** Linear Algebra, Random Module, File I/O, Structured Arrays, Performance Optimization, Real-World Projects, and Advanced Interview Questions.
