# 📘 NumPy Masterclass – Part 1
# Foundations of NumPy (Beginner → Intermediate)

This notebook introduces NumPy from absolute basics and builds a strong foundation for data science, machine learning, and AI.


## 1. Why NumPy?

Python lists are flexible but slow for numerical computation.

NumPy provides:
- Fast numerical operations
- Efficient memory usage
- Vectorized computation
- Multidimensional arrays (`ndarray`)


## 2. Installing NumPy

In [ ]:
# pip install numpy

# Import NumPy with standard alias np
import numpy as np

# Check installed NumPy version
print(np.__version__)

## 3. What is an ndarray?

`ndarray` (N-dimensional array) is the core data structure of NumPy.

Advantages:
- Homogeneous data
- Contiguous memory
- Fast mathematical operations


In [1]:
# Import NumPy with standard alias np
import numpy as np

# Create a NumPy array from a Python list
arr = np.array([10,20,30,40])

print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


## 4. Creating Arrays

In [3]:
# Import NumPy with standard alias np
import numpy as np

print(np.array([1,2,3]))
# Create array filled with zeros
print(np.zeros(5))
# Create array filled with ones
print(np.ones(5))
# Create array filled with a specific value
print(np.full(5,100))
# Create uninitialized array (random values from memory)
print(np.empty(3)) # It creates an array by allocating memory without initializing its values.

[1 2 3]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[100 100 100 100 100]
[4.9e-324 9.9e-324 1.5e-323]


In [ ]:
print(np.arange(1,11))
# Creates numbers from 1 to 10 (11 is excluded).
print(np.arange(0,20,2))
# Creates numbers from 0 to 18 with a step of 2.
print(np.linspace(0,1,5))
# Creates 5 evenly spaced numbers between 0 and 1 (both included).

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [2]:
# Create identity matrix (1s on diagonal, 0s elsewhere)
print(np.eye(4))
# Create square identity matrix
print(np.identity(3))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
print(np.identity(3,5))

TypeError: Cannot interpret '5' as a data type

In [3]:
print(np.eye(3, 5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## 5. Random Arrays

In [5]:
# Import NumPy with standard alias np
import numpy as np

# Generate random floats between 0 and 1
print(np.random.rand(3))
# Generate random integers in a range
print(np.random.randint(1,100,5))
# Generate random numbers from standard normal distribution
print(np.random.randn(5))

[0.84415177 0.77759407 0.31214564]
[78 54 26 37  1]
[-0.18246504 -0.13861149 -0.41916724  0.9989413  -0.41018814]


## 6. Array Attributes

In [7]:
# Create a NumPy array from a Python list
arr=np.array([[1,2,3],[4,5,6]])

print(arr)
# Print array shape (rows, columns)
print("Shape:",arr.shape)
# Print number of dimensions
print("Dimensions:",arr.ndim)
# Print total number of elements
print("Size:",arr.size)
# Print data type of array elements
print("Data Type:",arr.dtype)


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


## 7. Data Types

In [8]:
# Create a NumPy array from a Python list
arr=np.array([1,2,3],dtype=float)
print(arr)
# Print data type of array elements
print(arr.dtype)

# Convert array to a different data type
print(arr.astype(int))

[1. 2. 3.]
float64
[1 2 3]


## 8. Indexing

In [9]:
# Create a NumPy array from a Python list
arr=np.array([10,20,30,40,50])

# Index array by position (0-based)
print(arr[0])
# Index array by position (0-based)
print(arr[-1])

10
50


In [10]:
# Create a NumPy array from a Python list
matrix=np.array([[1,2,3],[4,5,6]])

print(matrix[0,1])
print(matrix[1,2])

2
6


## 9. Slicing

In [7]:
# Create array with evenly spaced values (start, stop, step)
arr=np.arange(10)

# Slice array [start:stop:step]
print(arr[2:7])
# Slice array [start:stop:step]
print(arr[:5])
# Slice array [start:stop:step]
print(arr[::2])
# Slice array [start:stop:step]
print(arr[::-1])

[2 3 4 5 6]
[0 1 2 3 4]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [12]:
# Create array with evenly spaced values (start, stop, step)
matrix=np.arange(1,10).reshape(3,3)

print(matrix)
print("*"*50)
print(matrix[:,:])
print("*"*50)

print(matrix[:,1])
print("*"*50)

print(matrix[1,:])
print("*"*50)

print(matrix[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[2 5 8]
**************************************************
[4 5 6]
**************************************************
[[1 2]
 [4 5]]


## 10. Reshaping Arrays

In [13]:
# Create array with evenly spaced values (start, stop, step)
arr=np.arange(12)

# Reshape array to new dimensions (total elements must match)
print(arr.reshape(3,4))
# Reshape array to new dimensions (total elements must match)
print(arr.reshape(2,6))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [14]:
# Create array with evenly spaced values (start, stop, step)
arr=np.arange(6).reshape(2,3)

# Flatten multi-dimensional array to 1D (returns copy)
print(arr.flatten())
# Flatten to 1D (returns view when possible, faster)
print(arr.ravel())
# Transpose array (swap rows and columns)
print(arr.T)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]


## 11. Copy vs View

In [8]:
# Create a NumPy array from a Python list
arr=np.array([1,2,3])

# Create a view (shares data with original)
view=arr.view()
# Create a deep copy (independent data)
copy=arr.copy()

arr[0]=999

print(arr)
print(view)
print(copy)

[999   2   3]
[999   2   3]
[1 2 3]


# Copy vs View

- **Copy**: Makes a completely new array with its own data.
- Changes to the copy do not affect the original.
- Changes to the original do not affect the copy.

- **View**: Makes a new array object that uses the same data as the original.
- Changes to the view affect the original.
- Changes to the original affect the view.

## 12. Basic Mathematical Operations

In [ ]:
# Create a NumPy array from a Python list
a=np.array([1,2,3])
# Create a NumPy array from a Python list
b=np.array([4,5,6])

# Element-wise operation between two arrays
print(a+b)
# Element-wise operation between two arrays
print(a-b)
# Element-wise operation between two arrays
print(a*b)
# Element-wise operation between two arrays
print(a/b)
# Element-wise power (square each element)
print(a**2)

## 13. Broadcasting Basics

In [9]:
# Create a NumPy array from a Python list
arr=np.array([1,2,3])

# Broadcasting: operation applied to every element
print(arr+10)
# Broadcasting: operation applied to every element
print(arr*5)

[11 12 13]
[ 5 10 15]


## 14. Mini Project - Student Marks Analysis

In [20]:
# Create a NumPy array from a Python list
marks=np.array([78,90,85,67,92])

print("Marks:",marks)
# Calculate the mean (average) of array elements
print("Average:",marks.mean())
# Find the maximum value in the array
print("Highest:",marks.max())
# Find the minimum value in the array
print("Lowest:",marks.min())

Marks: [78 90 85 67 92]
Average: 82.4
Highest: 92
Lowest: 67


## 15. Common Mistakes

- Confusing Python lists with NumPy arrays
- Forgetting `import numpy as np`
- Assuming slicing creates a copy
- Mixing incompatible shapes


## 16. Practice Exercises

1. Create arrays using every creation function.
2. Generate a 5×5 identity matrix.
3. Create random integers from 1–100.
4. Reshape a 1D array into 3×4.
5. Reverse an array.
6. Find array attributes.
7. Convert float array to integer.
8. Create a checkerboard matrix.


## 17. Interview Questions

1. Why is NumPy faster than Python lists?
2. What is `ndarray`?
3. Difference between `arange()` and `linspace()`?
4. Difference between `flatten()` and `ravel()`?
5. Difference between copy and view?
6. What is broadcasting?


# 🎉 Summary

You learned:
- NumPy basics
- Creating arrays
- Random arrays
- Array attributes
- Data types
- Indexing & slicing
- Reshaping
- Copy vs View
- Basic arithmetic
- Broadcasting basics

➡️ Next Notebook:
Vectorization, Universal Functions, Boolean Masking, Fancy Indexing, Sorting, Searching, Aggregations, Axis, Stacking & Splitting.
